/*
 * SkillTrack API
 * Backend API for logging daily learning activities, retrieving summaries, and generating AI insights. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sou.api;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.reflect.TypeToken;
import com.sou.model.LearningLog;
import com.sou.model.LearningLogInput;
import com.sou.sou.ApiCallback;
import com.sou.sou.ApiClient;
import com.sou.sou.ApiException;
import com.sou.sou.ApiResponse;
import com.sou.sou.Configuration;
import com.sou.sou.Pair;

public class LogsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LogsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public LogsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for addLearningLog
     * @param learningLogInput  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created log </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLearningLogCall( LearningLogInput learningLogInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = learningLogInput;

        // create path and map variables
        String localVarPath = "/logs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call addLearningLogValidateBeforeCall( LearningLogInput learningLogInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'learningLogInput' is set
        if (learningLogInput == null) {
            throw new ApiException("Missing the required parameter 'learningLogInput' when calling addLearningLog(Async)");
        }

        return addLearningLogCall(learningLogInput, _callback);

    }

    /**
     * Add a new learning log
     * 
     * @param learningLogInput  (required)
     * @return LearningLog
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created log </td><td>  -  </td></tr>
     </table>
     */
    public LearningLog addLearningLog( LearningLogInput learningLogInput) throws ApiException {
        ApiResponse<LearningLog> localVarResp = addLearningLogWithHttpInfo(learningLogInput);
        return localVarResp.getData();
    }

    /**
     * Add a new learning log
     * 
     * @param learningLogInput  (required)
     * @return ApiResponse&lt;LearningLog&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created log </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<LearningLog> addLearningLogWithHttpInfo( LearningLogInput learningLogInput) throws ApiException {
        okhttp3.Call localVarCall = addLearningLogValidateBeforeCall(learningLogInput, null);
        Type localVarReturnType = new TypeToken<LearningLog>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Add a new learning log (asynchronously)
     * 
     * @param learningLogInput  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Created log </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call addLearningLogAsync( LearningLogInput learningLogInput, final ApiCallback<LearningLog> _callback) throws ApiException {

        okhttp3.Call localVarCall = addLearningLogValidateBeforeCall(learningLogInput, _callback);
        Type localVarReturnType = new TypeToken<LearningLog>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getLearningLogs
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of learning logs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLearningLogsCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/logs";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLearningLogsValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getLearningLogsCall(_callback);

    }

    /**
     * Get all learning logs
     * 
     * @return List&lt;LearningLog&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of learning logs </td><td>  -  </td></tr>
     </table>
     */
    public List<LearningLog> getLearningLogs() throws ApiException {
        ApiResponse<List<LearningLog>> localVarResp = getLearningLogsWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Get all learning logs
     * 
     * @return ApiResponse&lt;List&lt;LearningLog&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of learning logs </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<LearningLog>> getLearningLogsWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getLearningLogsValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<LearningLog>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get all learning logs (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of learning logs </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getLearningLogsAsync(final ApiCallback<List<LearningLog>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLearningLogsValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<LearningLog>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
