quarkus:
  openapi-generator:
    codegen:
      spec:
        openapi_yml:
          model-name-prefix: "QuarkusOpenApiGenerator"

  swagger-ui:
    always-include: true
    path: /swagger

  http:
    cors: true

  datasource:
    db-kind: postgresql
    username: skilluser
    password: fireball
    jdbc:
      url: jdbc:postgresql://localhost:5432/skilltrack

  hibernate-orm:
    database:
      generation: drop-and-create # use 'update' for dev
    log:
      sql: true

openai:
  api:
    key: ${openai_api}
    url: https://api.openai.com/v1/chat/completions
