quarkus:
  swagger-ui:
    always-include: true
    path: /swagger

  datasource:
    db-kind: postgresql
    username: ${DB_PASSWORD:skilluser}
    password: ${DB_PASSWORD:fireball}
    jdbc:
      url: jdbc:postgresql://localhost:5432/${DB_NAME:skilltrack}

  hibernate-orm:
    log:
      sql: true

  http:
    auth:
      basic: true
      policy:
        roles-allowed:
          roles-allowed: admin,user


openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
