quarkus:
  datasource:
    db-kind: postgresql
    username: skilluser
    password: fireball
    jdbc:
      url: jdbc:postgresql://localhost:5432/skilltrack

  hibernate-orm:
    log:
      sql: true

  swagger-ui:
    always-include: true
    path: /swagger

  http:
    cors: true

openai:
  api:
    key: ${openai_api}
    url: https://api.openai.com/v1/chat/completions