version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: skilltrack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: skilluser
      POSTGRES_PASSWORD: fireball
      POSTGRES_DB: skilltrack
    ports:
      - "5432:5432"
    volumes:
      - skilltrack-db-data:/var/lib/postgresql/data
    networks:
      - skilltrack-net

volumes:
  skilltrack-db-data:

networks:
  skilltrack-net:
