/*
 * SkillTrack API
 * Backend API for logging daily learning activities, retrieving summaries, and generating AI insights. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sou.api;

import java.util.List;

import com.sou.sou.ApiException;
import com.sou.sou.api.AiApi;
import com.sou.sou.model.LearningLog;
import com.sou.sou.model.SummaryResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for AiApi
 */
@Disabled
public class AiApiTest {

    private final AiApi api = new AiApi();

    /**
     * Get AI summary of recent logs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void summarizeLogsTest() throws ApiException {
        List<LearningLog> learningLog = null;
        SummaryResponse response = api.summarizeLogs(learningLog);
        // TODO: test validations
    }

}
