/*
 * SkillTrack API
 * Backend API for logging daily learning activities, retrieving summaries, and generating AI insights. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sou.api;

import java.util.List;

import com.sou.sou.ApiException;
import com.sou.sou.api.LogsApi;
import com.sou.sou.model.LearningLog;
import com.sou.sou.model.LearningLogInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * API tests for LogsApi
 */
@Disabled
public class LogsApiTest {

    private final LogsApi api = new LogsApi();

    /**
     * Add a new learning log
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addLearningLogTest() throws ApiException {
        LearningLogInput learningLogInput = null;
        LearningLog response = api.addLearningLog(learningLogInput);
        // TODO: test validations
    }

    /**
     * Get all learning logs
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLearningLogsTest() throws ApiException {
        List<LearningLog> response = api.getLearningLogs();
        // TODO: test validations
    }

}
