name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Set up environment variables
        run: echo "TEST_USER=${{ secrets.TEST_USER }}" >> $GITHUB_ENV
        env:
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

      - name: Build and test
        env:
          TEST_DB_USER: ${{ secrets.DB_USER }}
          TEST_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          TEST_DB_NAME: ${{ secrets.DB_NAME }}

        run: ./mvnw clean verify -B
